e_stat:
  target: default
  outputs:
    default:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: e_stat
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
        - spatial
      attach:
        - path: "md:e_stat"
          alias: e_stat
          is_ducklake: true
    local:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: e_stat
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
        - spatial
      attach:
        - path: "md:dev_e_stat"
          alias: e_stat
          is_ducklake: true
